patterns:
  deny:
    - regex: '^(st-|St)'
      message: Commit message subject should not be prefixed with 'st-' or 'St', use 'st/' instead
      where: subject
    - regex: '^[^:]+: [a-z]'
      message: "Commit message subject should be properly Capitalized. E.g. 'window: Marginalize extradicity'"
      where: subject
    - regex: '^\S*\.(js|c|h):'
      message: Commit message subject prefix should not include .c, .h etc.
      where: subject
    - regex: '([^.]\.|[:,;])\s*$'
      message: Commit message subject should not end with punctuation
      where: subject
